{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - riot.{{ .Values.domain }}
{{ end }}
