{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: element-web
spec:
  secretName: element-web-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - riot.{{ .Values.domain }}
{{ end }}
