apiVersion: v1
kind: Service
metadata:
  name: element-web
  labels:
    app: element-web
spec:
  ports:
  - name: http
    port: {{ .Values.port }}
    targetPort: 80
  selector:
    app: element-web
