apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-settings
data:
  settings.yaml: |
    admins:
    - "{{ .Values.admins }}"
    mods:
    - "{{ .Values.mods }}"
    domains:
    - "{{ .Values.domain }}"
  privsettings.yaml: |
    token: "{{ .Values.bot_token }}"
