environment: production

domain: w3f.tech
matrixDomain: web3.foundation

brand: "Web3 Foundation"

port: 8080

image:
  repo: vectorim/element-web

replicaCount: 3  

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 9
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

resources:
  requests:
    cpu: 5m
    memory: 15Mi  
