environment: production

port: 8008

domain: domain.com
proxied: false

image:
  repo: matrixdotorg/synapse
  #tag: latest

antiscam_image:
  repo: web3f/matrix-antiscam
  tag: latest

db:
  user: synapse_user
  password: password
  name: synapse
  host: postgresql

recaptcha:
  publicKey: recaptcha_public
  privateKey: recaptcha_private

macaroonSecretKey: macaroon_secret
formSecret: form_secret

signingKey: signing_key

emailPattern: |-
  .*@domain\.com

autojoinRooms:
- "#arrivals:domain.com"

registrationSharedSecret: foobar

sso:
  enabled: false
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET

email:
  enabled: true
  smtp_host: "localhost"
  smtp_port: 25
  smtp_user: "user"
  smtp_pass: "password"
  notif_from: "Your Matrix Server"
  client_base_url: "http://localhost/riot"

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi  
