environment: production

port: 8008

domain: domain.com

image:
  repo: matrixdotorg/synapse
  tag: v1.37.1

antiscam_image:
  repo: web3f/matrix-antiscam
  tag: latest

db:
  user: synapse_user
  password: password
  name: synapse
  host: postgresql-postgresql

recaptcha:
  publicKey: recaptcha_public
  privateKey: recaptcha_private

macaroonSecretKey: macaroon_secret
formSecret: form_secret

signingKey: signing_key

emailPattern: |-
  .*@domain\.com

autojoinRooms:
- "#arrivals:domain.com"

antiscam: false

registrationSharedSecret: foobar

email:
  enabled: false
  smtp_host: "localhost"
  smtp_port: 25
  smtp_user: "user"
  smtp_pass: "password"
  notif_from: "Your Matrix Server"
  riot_base_url: "http://localhost/riot"

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi  
