environments:
  production:
  ci:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgresql
    chart: bitnami/postgresql
    version: ^11.9.11
    values:
      - ./config/postgresql-values.yaml.gotmpl
