environments:
  production:
  ci:
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: postgresql
    chart: bitnami/postgresql
    version: 10.14.0
    values:
      - ./config/postgresql-values.yaml.gotmpl
