environments:
  production:
  ci:

releases:
- name: matrix-server
  chart: ../charts/matrix-server
  values:
  - environment: {{ .Environment.Name }}
  - db:
      user: {{ env "DB_USER" | default "synapse_user" }}
      password: '{{ env "DB_PASSWORD" | default "pass" }}'
      name: {{ env "DB_NAME" | default "synapse" }}
    recaptcha:
      publicKey: {{ env "RECAPTCHA_PUBLIC_KEY" | default "recaptcha_public" }}
      privateKey: {{ env "RECAPTCHA_PRIVATE_KEY" | default "recaptcha_private" }}
    macaroonSecretKey: {{ env "MACAROON_SECRET_KEY" | default "macaroon_secret" }}
    formSecret: {{ env "FORM_SECRET" | default "form_secret" }}
    signingKey: {{ env "SIGNING_KEY" | default "signing_key" | quote }}

- name: element-web
  chart: ../charts/element-web
  values:
  - environment: {{ .Environment.Name }}

{{ if env "ENABLE_ANTISCAM" }}
- name: matrix-antiscam-bot
  chart: ../charts/matrix-antiscam-bot
  values:
  - environment: {{ .Environment.Name }}
  - bot_token: {{ env "BOT_TOKEN" | default "bot_token" }}
  - admins: {{ env "BOT_ADMINS" | default "bot_admins" }}
  - mods: {{ env "BOT_MODS" | default "bot_mods" }}
  - domain: {{ env "BOT_DOMAIN" | default "bot_domain" }}
{{ end }}
