{{ if ne .Values.environment "ci" }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Release.name }}
spec:
  secretName: {{ .Release.name }}-tls
  issuerRef:
    name: letsencrypt
  dnsNames:
  - matrix.{{ .Values.domain }}
{{ end }}
